# Generated by Django 5.1.13 on 2025-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prueba',
            field=models.CharField(default='valor por defecto', max_length=100),
        ),
    ]
